rootProject.name = "android-movie-lib"
include(":app")
include(":data")
include(":domain")
include(":util")
include(":presentation")
include(":baseui")
include(":data:local")
include(":data:remote")
include(":data:preferences")
include(":data:repository")
